# Generated by Django 2.2.24 on 2021-10-25 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='check_list',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('is_completed', models.BooleanField(default=False)),
                ('todo_content', models.CharField(max_length=200)),
                ('is_Pin', models.BooleanField(default=True)),
            ],
        ),
    ]
